import "./globals.css";
import { Footer, Nav } from "@/components";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
